[2025-04-08T18:43:17.470+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: elt_pipeline.create_bucket scheduled__2025-04-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
