[2025-04-09T08:27:10.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T08:27:10.602+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.last_load_test_string scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T08:27:10.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.last_load_test_string scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T08:27:10.613+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-09T08:27:10.629+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): last_load_test_string> on 2025-04-08 00:00:00+00:00
[2025-04-09T08:27:10.638+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=811) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T08:27:10.639+0000] {standard_task_runner.py:63} INFO - Started process 829 to run task
[2025-04-09T08:27:10.639+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'last_load_test_string', 'scheduled__2025-04-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpd1hjjvoi']
[2025-04-09T08:27:10.642+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask last_load_test_string
[2025-04-09T08:27:10.664+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-09T08:27:10.705+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.last_load_test_string scheduled__2025-04-08T00:00:00+00:00 [running]> on host 208e59669cb5
[2025-04-09T08:27:10.801+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='last_load_test_string' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T00:00:00+00:00'
[2025-04-09T08:27:10.802+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T08:27:11.248+0000] {extractor.py:97} INFO - Last load date: 2021-01-03
[2025-04-09T08:27:11.249+0000] {extractor.py:98} INFO - Next load date: 2021-01-04
[2025-04-09T08:27:11.254+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-09T08:27:11.255+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T08:27:11.265+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=last_load_test_string, run_id=scheduled__2025-04-08T00:00:00+00:00, execution_date=20250408T000000, start_date=20250409T082710, end_date=20250409T082711
[2025-04-09T08:27:11.295+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-09T08:27:11.316+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-09T08:27:11.320+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-09T09:43:02.522+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T09:43:02.560+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.last_load_test_string scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T09:43:02.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.last_load_test_string scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T09:43:02.570+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-09T09:43:02.589+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): last_load_test_string> on 2025-04-08 00:00:00+00:00
[2025-04-09T09:43:02.596+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=486) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T09:43:02.598+0000] {standard_task_runner.py:63} INFO - Started process 498 to run task
[2025-04-09T09:43:02.596+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'last_load_test_string', 'scheduled__2025-04-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmprp4d15yh']
[2025-04-09T09:43:02.598+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask last_load_test_string
[2025-04-09T09:43:02.620+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-09T09:43:02.670+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.last_load_test_string scheduled__2025-04-08T00:00:00+00:00 [running]> on host b3f1192a97c8
[2025-04-09T09:43:02.787+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='last_load_test_string' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T00:00:00+00:00'
[2025-04-09T09:43:02.789+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T09:43:02.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T09:43:02.827+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/test_last_load.py", line 5, in test_get_last_load_returns_string
    result = coin_extractor.get_last_load()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/extractor.py", line 90, in get_last_load
    conn = duckdb.connect(db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/data/historical_bitcoin.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 336). See also https://duckdb.org/docs/connect/concurrency
[2025-04-09T09:43:02.858+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=last_load_test_string, run_id=scheduled__2025-04-08T00:00:00+00:00, execution_date=20250408T000000, start_date=20250409T094302, end_date=20250409T094302
[2025-04-09T09:43:02.876+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task last_load_test_string (IO Error: Could not set lock on file "/opt/***/data/historical_bitcoin.db": Conflicting lock is held in /usr/local/bin/python3.12 (PID 336). See also https://duckdb.org/docs/connect/concurrency; 498)
[2025-04-09T09:43:02.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-09T09:43:02.957+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T09:43:02.959+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
