[2025-04-05T17:01:30.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T17:01:30.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_streamlit.run_streamlit_app manual__2025-04-05T17:01:29.599623+00:00 [queued]>
[2025-04-05T17:01:30.377+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_streamlit.run_streamlit_app manual__2025-04-05T17:01:29.599623+00:00 [queued]>
[2025-04-05T17:01:30.379+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T17:01:30.394+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_streamlit_app> on 2025-04-05 17:01:29.599623+00:00
[2025-04-05T17:01:30.404+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_streamlit', 'run_streamlit_app', 'manual__2025-04-05T17:01:29.599623+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/run_streamlit.py', '--cfg-path', '/tmp/tmpt9wxdcyv']
[2025-04-05T17:01:30.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1658) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T17:01:30.407+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask run_streamlit_app
[2025-04-05T17:01:30.407+0000] {standard_task_runner.py:63} INFO - Started process 1659 to run task
[2025-04-05T17:01:30.431+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T17:01:30.482+0000] {task_command.py:426} INFO - Running <TaskInstance: run_streamlit.run_streamlit_app manual__2025-04-05T17:01:29.599623+00:00 [running]> on host 1f8025531576
[2025-04-05T17:01:30.588+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_streamlit' AIRFLOW_CTX_TASK_ID='run_streamlit_app' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T17:01:29.599623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T17:01:29.599623+00:00'
[2025-04-05T17:01:30.589+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T17:01:30.606+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T17:01:30.608+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run /opt/***/visualization/dashboard.py --server.enableWebsocketCompression=false --server.enableCORS=false"']
[2025-04-05T17:01:30.619+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T17:01:30.620+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2025-04-05T17:01:30.621+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-05T17:01:30.622+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T17:01:30.638+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-05T17:01:30.644+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=run_streamlit, task_id=run_streamlit_app, run_id=manual__2025-04-05T17:01:29.599623+00:00, execution_date=20250405T170129, start_date=20250405T170130, end_date=20250405T170130
[2025-04-05T17:01:30.656+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task run_streamlit_app (Bash command failed. The command returned a non-zero exit code 2.; 1659)
[2025-04-05T17:01:30.711+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T17:01:30.736+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T17:01:30.739+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
