[2025-04-08T19:25:16.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T19:25:16.838+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_streamlit.run_streamlit_app manual__2025-04-08T19:25:15.555451+00:00 [queued]>
[2025-04-08T19:25:16.846+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_streamlit.run_streamlit_app manual__2025-04-08T19:25:15.555451+00:00 [queued]>
[2025-04-08T19:25:16.847+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-08T19:25:16.860+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_streamlit_app> on 2025-04-08 19:25:15.555451+00:00
[2025-04-08T19:25:16.867+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_streamlit', 'run_streamlit_app', 'manual__2025-04-08T19:25:15.555451+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/run_streamlit.py', '--cfg-path', '/tmp/tmp8gwhkvpg']
[2025-04-08T19:25:16.867+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1537) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T19:25:16.869+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask run_streamlit_app
[2025-04-08T19:25:16.869+0000] {standard_task_runner.py:63} INFO - Started process 1538 to run task
[2025-04-08T19:25:16.887+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-08T19:25:16.927+0000] {task_command.py:426} INFO - Running <TaskInstance: run_streamlit.run_streamlit_app manual__2025-04-08T19:25:15.555451+00:00 [running]> on host 01b011050d21
[2025-04-08T19:25:17.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_streamlit' AIRFLOW_CTX_TASK_ID='run_streamlit_app' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T19:25:15.555451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T19:25:15.555451+00:00'
[2025-04-08T19:25:17.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T19:25:17.048+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-08T19:25:17.049+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run /opt/***/visualization/dashboard.py --server.enableWebsocketCompression=false --server.enableCORS=false']
[2025-04-08T19:25:17.060+0000] {subprocess.py:86} INFO - Output:
[2025-04-08T19:25:18.065+0000] {subprocess.py:93} INFO - 2025-04-08 19:25:18.064
[2025-04-08T19:25:18.066+0000] {subprocess.py:93} INFO - Warning: the config option 'server.enableCORS=false' is not compatible with 'server.enableXsrfProtection=true'.
[2025-04-08T19:25:18.066+0000] {subprocess.py:93} INFO - As a result, 'server.enableCORS' is being overridden to 'true'.
[2025-04-08T19:25:18.067+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.067+0000] {subprocess.py:93} INFO - More information:
[2025-04-08T19:25:18.068+0000] {subprocess.py:93} INFO - In order to protect against CSRF attacks, we send a cookie with each request.
[2025-04-08T19:25:18.068+0000] {subprocess.py:93} INFO - To do so, we must specify allowable origins, which places a restriction on
[2025-04-08T19:25:18.069+0000] {subprocess.py:93} INFO - cross-origin resource sharing.
[2025-04-08T19:25:18.069+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.070+0000] {subprocess.py:93} INFO - If cross origin resource sharing is required, please disable server.enableXsrfProtection.
[2025-04-08T19:25:18.070+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.070+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.071+0000] {subprocess.py:93} INFO - Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.
[2025-04-08T19:25:18.071+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.392+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.393+0000] {subprocess.py:93} INFO -   You can now view your Streamlit app in your browser.
[2025-04-08T19:25:18.394+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:25:18.395+0000] {subprocess.py:93} INFO -   Local URL: http://localhost:8502
[2025-04-08T19:25:18.395+0000] {subprocess.py:93} INFO -   Network URL: http://172.22.0.5:8502
[2025-04-08T19:25:18.396+0000] {subprocess.py:93} INFO -   External URL: http://194.110.77.14:8502
[2025-04-08T19:25:18.396+0000] {subprocess.py:93} INFO - 
[2025-04-08T19:33:38.243+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-04-08T19:33:38.246+0000] {process_utils.py:132} INFO - Sending 15 to group 1538. PIDs of all processes in the group: [1539, 1538]
[2025-04-08T19:33:38.247+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1538
[2025-04-08T19:33:38.248+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-08T19:33:38.249+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-08T19:33:38.251+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T19:33:38.275+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-08T19:33:38.286+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=run_streamlit, task_id=run_streamlit_app, run_id=manual__2025-04-08T19:25:15.555451+00:00, execution_date=20250408T192515, start_date=20250408T192516, end_date=20250408T193338
[2025-04-08T19:33:39.637+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1538, status='terminated', exitcode=2, started='19:25:16') (1538) terminated with exit code 2
[2025-04-08T19:33:39.639+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1539, status='terminated', started='19:25:16') (1539) terminated with exit code None
[2025-04-08T19:33:39.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-04-08T19:33:39.668+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T19:33:39.687+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
