[2025-04-05T16:36:33.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:36:33.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data manual__2025-04-05T16:36:28.100285+00:00 [queued]>
[2025-04-05T16:36:33.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data manual__2025-04-05T16:36:28.100285+00:00 [queued]>
[2025-04-05T16:36:33.465+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:36:33.484+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-05 16:36:28.100285+00:00
[2025-04-05T16:36:33.497+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=739) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:36:33.496+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'manual__2025-04-05T16:36:28.100285+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpnkeo_vjl']
[2025-04-05T16:36:33.498+0000] {standard_task_runner.py:63} INFO - Started process 751 to run task
[2025-04-05T16:36:33.498+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask load_data
[2025-04-05T16:36:33.525+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:36:33.579+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data manual__2025-04-05T16:36:28.100285+00:00 [running]> on host d060e19f414c
[2025-04-05T16:36:33.739+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T16:36:28.100285+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T16:36:28.100285+00:00'
[2025-04-05T16:36:33.740+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:36:33.777+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T16:36:33.778+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:36:33.780+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:36:33.820+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=manual__2025-04-05T16:36:28.100285+00:00, execution_date=20250405T163628, start_date=20250405T163633, end_date=20250405T163633
[2025-04-05T16:36:33.874+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:36:33.894+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:36:33.896+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
