[2025-04-05T10:45:18.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T10:45:18.865+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data manual__2025-04-05T10:45:11.558526+00:00 [queued]>
[2025-04-05T10:45:18.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data manual__2025-04-05T10:45:11.558526+00:00 [queued]>
[2025-04-05T10:45:18.875+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T10:45:18.891+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-05 10:45:11.558526+00:00
[2025-04-05T10:45:18.900+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=322) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T10:45:18.901+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'manual__2025-04-05T10:45:11.558526+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpulhlh551']
[2025-04-05T10:45:18.919+0000] {standard_task_runner.py:63} INFO - Started process 346 to run task
[2025-04-05T10:45:18.919+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_data
[2025-04-05T10:45:18.940+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T10:45:18.982+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data manual__2025-04-05T10:45:11.558526+00:00 [running]> on host d56545bf874e
[2025-04-05T10:45:19.095+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T10:45:11.558526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T10:45:11.558526+00:00'
[2025-04-05T10:45:19.096+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T10:45:19.123+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T10:45:19.124+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T10:45:19.125+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T10:45:19.140+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=manual__2025-04-05T10:45:11.558526+00:00, execution_date=20250405T104511, start_date=20250405T104518, end_date=20250405T104519
[2025-04-05T10:45:19.176+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T10:45:19.194+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T10:45:19.199+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
