[2025-04-08T19:20:33.944+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T19:20:33.990+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data manual__2025-04-08T19:15:31.276161+00:00 [queued]>
[2025-04-08T19:20:33.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data manual__2025-04-08T19:15:31.276161+00:00 [queued]>
[2025-04-08T19:20:34.000+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-08T19:20:34.028+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-08 19:15:31.276161+00:00
[2025-04-08T19:20:34.039+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1018) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T19:20:34.042+0000] {standard_task_runner.py:63} INFO - Started process 1042 to run task
[2025-04-08T19:20:34.040+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'manual__2025-04-08T19:15:31.276161+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp97i0p_d_']
[2025-04-08T19:20:34.043+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask get_coin_data
[2025-04-08T19:20:34.066+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-08T19:20:34.107+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data manual__2025-04-08T19:15:31.276161+00:00 [running]> on host 01b011050d21
[2025-04-08T19:20:34.200+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T19:15:31.276161+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T19:15:31.276161+00:00'
[2025-04-08T19:20:34.202+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T19:20:34.227+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T19:20:34.227+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_pipeline.py", line 29, in get_coin_data_task
    coin_extractor = CoinDataExtractor(asset_id, last_load)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/extractor.py", line 20, in __init__
    self.start_date = datetime.strptime(start_date,"%Y-%m-%d")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
[2025-04-08T19:20:34.244+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=elt_pipeline, task_id=get_coin_data, run_id=manual__2025-04-08T19:15:31.276161+00:00, execution_date=20250408T191531, start_date=20250408T192033, end_date=20250408T192034
[2025-04-08T19:20:34.253+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task get_coin_data (strptime() argument 1 must be str, not None; 1042)
[2025-04-08T19:20:34.297+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-08T19:20:34.321+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T19:20:34.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
