[2025-04-09T09:21:34.120+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T09:21:34.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data_from_minio_to_duckdb manual__2025-04-09T09:21:33.278944+00:00 [queued]>
[2025-04-09T09:21:34.171+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data_from_minio_to_duckdb manual__2025-04-09T09:21:33.278944+00:00 [queued]>
[2025-04-09T09:21:34.172+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-09T09:21:34.189+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_from_minio_to_duckdb> on 2025-04-09 09:21:33.278944+00:00
[2025-04-09T09:21:34.199+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7226) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T09:21:34.200+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data_from_minio_to_duckdb', 'manual__2025-04-09T09:21:33.278944+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp832u89z1']
[2025-04-09T09:21:34.200+0000] {standard_task_runner.py:63} INFO - Started process 7249 to run task
[2025-04-09T09:21:34.201+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask load_data_from_minio_to_duckdb
[2025-04-09T09:21:34.220+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-09T09:21:34.266+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data_from_minio_to_duckdb manual__2025-04-09T09:21:33.278944+00:00 [running]> on host 208e59669cb5
[2025-04-09T09:21:34.383+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data_from_minio_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T09:21:33.278944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T09:21:33.278944+00:00'
[2025-04-09T09:21:34.384+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T09:21:34.888+0000] {extractor.py:97} INFO - Last load date: 2021-01-04
[2025-04-09T09:21:34.889+0000] {extractor.py:98} INFO - Next load date: 2021-01-05
[2025-04-09T09:21:34.895+0000] {init_minio.py:24} INFO - Minio client connected successfully
[2025-04-09T09:21:34.913+0000] {extractor.py:147} ERROR - Error loading data to DuckDB: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /bitcoin/bitcoin-2021-01-05, request_id: 18349C0395DF773C, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: bitcoin, object_name: bitcoin-2021-01-05
[2025-04-09T09:21:34.913+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T09:21:34.914+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_pipeline.py", line 41, in load_data_from_minio_to_duckdb_task
    coin_extractor.load_data_from_minio_to_duckdb()
  File "/opt/airflow/scripts/extractor.py", line 117, in load_data_from_minio_to_duckdb
    minio_client.fget_object(self.asset_id, self.file_name,local_file_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1119, in fget_object
    stat = self.stat_object(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 2123, in stat_object
    response = self._execute(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 441, in _execute
    return self._url_open(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 424, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /bitcoin/bitcoin-2021-01-05, request_id: 18349C0395DF773C, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: bitcoin, object_name: bitcoin-2021-01-05
[2025-04-09T09:21:34.934+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=load_data_from_minio_to_duckdb, run_id=manual__2025-04-09T09:21:33.278944+00:00, execution_date=20250409T092133, start_date=20250409T092134, end_date=20250409T092134
[2025-04-09T09:21:34.948+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task load_data_from_minio_to_duckdb (S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /bitcoin/bitcoin-2021-01-05, request_id: 18349C0395DF773C, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: bitcoin, object_name: bitcoin-2021-01-05; 7249)
[2025-04-09T09:21:34.977+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-09T09:21:34.997+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T09:21:35.001+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
