[2025-04-08T19:15:32.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T19:15:32.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-08T19:15:32.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-08T19:15:32.364+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-08T19:15:32.380+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-07 00:00:00+00:00
[2025-04-08T19:15:32.390+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=460) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T19:15:32.393+0000] {standard_task_runner.py:63} INFO - Started process 485 to run task
[2025-04-08T19:15:32.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-07T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpblmsar1y']
[2025-04-08T19:15:32.394+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask get_coin_data
[2025-04-08T19:15:32.418+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-08T19:15:32.473+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-07T00:00:00+00:00 [running]> on host 01b011050d21
[2025-04-08T19:15:32.581+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T00:00:00+00:00'
[2025-04-08T19:15:32.582+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T19:15:32.611+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T19:15:32.612+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_pipeline.py", line 29, in get_coin_data_task
    coin_extractor = CoinDataExtractor(asset_id, last_load)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/extractor.py", line 20, in __init__
    self.start_date = datetime.strptime(start_date,"%Y-%m-%d")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
[2025-04-08T19:15:32.637+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-07T00:00:00+00:00, execution_date=20250407T000000, start_date=20250408T191532, end_date=20250408T191532
[2025-04-08T19:15:32.650+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task get_coin_data (strptime() argument 1 must be str, not None; 485)
[2025-04-08T19:15:32.689+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-08T19:15:32.717+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T19:15:32.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
